# Generated by Django 3.2.5 on 2021-07-02 08:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 8, 35, 24, 180766, tzinfo=utc)),
        ),
    ]
